import { useState, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileUploadSection } from "./components/file-upload-section";
import { SettingsSection } from "./components/settings-section";
import { CircuitBoard, Download, Play, Clock, Route, Scissors } from "lucide-react";

interface FileItem {
  id: string;
  name: string;
  size: number;
  type: "copper" | "mask" | "drill";
  content: string;
  status: "pending" | "loaded" | "error";
  error?: string;
}

interface GerberSettings {
  toolDiameter: number;
  toolAperture: number;
  feedRate: number;
  plungeRate: number;
  retractRate: number;
  zSafe: number;
  zPlunge: number;
  zRetract: number;
  isolationWidth: number;
  boardThickness: number;
  useAperture: boolean;
  mergeArcs: boolean;
  reversePath: boolean;
  convertPadsToRects: boolean;
}

const defaultSettings: GerberSettings = {
  toolDiameter: 0.2,
  toolAperture: 0.8,
  feedRate: 100,
  plungeRate: 50,
  retractRate: 200,
  zSafe: 2,
  zPlunge: -0.1,
  zRetract: 1,
  isolationWidth: 0.15,
  boardThickness: 1.6,
  useAperture: true,
  mergeArcs: true,
  reversePath: false,
  convertPadsToRects: true,
};

function parseGerberToGcode(
  copperContent: string,
  settings: GerberSettings
): { gcode: string; stats: { lines: number; cuts: number; arcs: number; time: number } } {
  const lines: string[] = [];
  
  // Header
  lines.push("%");
  lines.push("(Generated by CNC Utils - Gerber to Gcode)");
  lines.push("G21 (mm mode)");
  lines.push("G90 (absolute mode)");
  lines.push("G28 (home)");
  lines.push("G00 Z" + settings.zSafe + " (retract to safe height)");
  
  // Parse Gerber content - extract coordinates
  const coordRegex = /X([-\d.]+)Y([-\d.]+)/gi;
  
  const coords: { x: number; y: number }[] = [];
  let match;
  
  // Extract coordinates from Gerber file
  while ((match = coordRegex.exec(copperContent)) !== null) {
    coords.push({
      x: parseFloat(match[1]) / 1000,
      y: parseFloat(match[2]) / 1000,
    });
  }
  
  // If coordinates are very small, they might already be in mm
  const maxCoord = coords.length > 0 ? Math.max(...coords.map(c => Math.max(Math.abs(c.x), Math.abs(c.y)))) : 0;
  if (maxCoord < 100 && maxCoord > 0) {
    coords.forEach(c => {
      c.x *= 1000;
      c.y *= 1000;
    });
  }
  
  // Reverse path if needed
  if (settings.reversePath) {
    coords.reverse();
  }
  
  // Generate toolpath
  if (coords.length > 0) {
    lines.push("(Toolpath with " + coords.length + " points)");
    lines.push("G00 X0 Y0");
    
    // Move to first point
    lines.push("G00 Z" + settings.zSafe);
    lines.push("G00 X" + coords[0].x.toFixed(3) + " Y" + coords[0].y.toFixed(3));
    
    // Plunge
    lines.push("G01 Z" + settings.zPlunge + " F" + settings.plungeRate);
    
    // Cut path
    for (let i = 1; i < coords.length; i++) {
      lines.push("G01 X" + coords[i].x.toFixed(3) + " Y" + coords[i].y.toFixed(3) + " F" + settings.feedRate);
    }
    
    // Retract
    lines.push("G00 Z" + settings.zRetract);
  }
  
  // Footer
  lines.push("G00 Z" + settings.zSafe);
  lines.push("G28 (return home)");
  lines.push("M5 (spindle off)");
  lines.push("M30 (end)");
  
  const gcode = lines.join("\n");
  const estimatedTime = (coords.length * 10) / settings.feedRate * 60;
  
  return {
    gcode,
    stats: {
      lines: gcode.split("\n").length,
      cuts: coords.length,
      arcs: 0,
      time: estimatedTime,
    },
  };
}

export default function GerberPage() {
  const [files, setFiles] = useState<FileItem[]>([]);
  const [settings, setSettings] = useState<GerberSettings>(defaultSettings);
  const [gcodeOutput, setGcodeOutput] = useState("");
  const [stats, setStats] = useState<{ lines: number; cuts: number; arcs: number; time: number } | null>(null);
  const [isConverting, setIsConverting] = useState(false);

  const copperFile = files.find((f) => f.type === "copper" && f.status === "loaded");
  
  const handleConvert = useCallback(() => {
    if (!copperFile) return;
    
    setIsConverting(true);
    
    setTimeout(() => {
      const result = parseGerberToGcode(copperFile.content, settings);
      setGcodeOutput(result.gcode);
      setStats(result.stats);
      setIsConverting(false);
    }, 500);
  }, [copperFile, settings]);

  const handleExport = useCallback(() => {
    if (!gcodeOutput) return;
    
    const blob = new Blob([gcodeOutput], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "pcb_ditong.gcode";
    a.click();
    URL.revokeObjectURL(url);
  }, [gcodeOutput]);

  const formatTime = (seconds: number) => {
    if (seconds < 60) return Math.round(seconds) + "s";
    const mins = Math.floor(seconds / 60);
    const secs = Math.round(seconds % 60);
    return mins + "m " + secs + "s";
  };

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-7xl mx-auto px-4 py-8 space-y-6">
        <header className="text-center space-y-2">
          <h1 className="text-3xl font-bold tracking-tight text-foreground">
            Gerber Zhuan Gcode
          </h1>
          <p className="text-muted-foreground">
            Jiang Gerber Wenjian Zhuanhwei Wei CNC Diaokeji Keyong De Gcode
          </p>
        </header>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Left column */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-lg">
                  <CircuitBoard className="w-5 h-5 text-primary" />
                  Gerber Wenjian
                </CardTitle>
              </CardHeader>
              <CardContent>
                <FileUploadSection files={files} onFilesChange={setFiles} />
              </CardContent>
            </Card>
            
            <SettingsSection value={settings} onChange={setSettings} />
          </div>

          {/* Right column */}
          <div className="space-y-6">
            {/* Preview */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-lg">
                  <Route className="w-5 h-5 text-primary" />
                  Zhuanhuan Yulan
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {stats ? (
                  <div className="grid grid-cols-2 gap-4">
                    <div className="p-4 bg-muted/50 rounded-lg text-center">
                      <div className="flex items-center justify-center gap-2 text-chart-1">
                        <Scissors className="w-4 h-4" />
                        <span className="text-2xl font-mono font-bold">{stats.cuts}</span>
                      </div>
                      <p className="text-xs text-muted-foreground mt-1">Qiexue Duanshu</p>
                    </div>
                    <div className="p-4 bg-muted/50 rounded-lg text-center">
                      <div className="flex items-center justify-center gap-2 text-chart-2">
                        <Clock className="w-4 h-4" />
                        <span className="text-2xl font-mono font-bold">{formatTime(stats.time)}</span>
                      </div>
                      <p className="text-xs text-muted-foreground mt-1">Yugu Shijian</p>
                    </div>
                  </div>
                ) : (
                  <div className="text-center py-8 text-muted-foreground">
                    <Route className="w-12 h-12 mx-auto mb-3 opacity-30" />
                    <p className="text-sm">Shangchuan Gerber Wenjian Hou Chakan Yulan</p>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Output */}
            <Card>
              <CardHeader className="pb-2">
                <div className="flex items-center justify-between">
                  <CardTitle className="flex items-center gap-2 text-lg">
                    <CircuitBoard className="w-5 h-5 text-primary" />
                    Gcode Shuchu
                  </CardTitle>
                  <div className="flex items-center gap-2">
                    {stats && (
                      <Badge variant="secondary" className="font-mono text-xs">
                        {stats.lines} Hang
                      </Badge>
                    )}
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={handleExport}
                      disabled={!gcodeOutput}
                    >
                      <Download className="w-4 h-4 mr-1" />
                      Daochu
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="relative">
                  <div className="bg-card rounded-lg border border-border overflow-hidden">
                    <div className="max-h-[400px] overflow-auto">
                      <pre className="p-4 font-mono text-xs whitespace-pre-wrap break-all text-muted-foreground">
                        {gcodeOutput || "(Dengdai Zhuanhuan...)"}
                      </pre>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Convert button */}
            <Button
              size="lg"
              className="w-full"
              onClick={handleConvert}
              disabled={!copperFile || isConverting}
            >
              {isConverting ? (
                <>Zhuanhuan Zhong...</>
              ) : (
                <>
                  <Play className="w-5 h-5 mr-2" />
                  Kaishi Zhuanhuan
                </>
              )}
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
