#!/usr/bin/env python3
"""
精确 STEP 切片器
使用 cadquery (OCP) 进行精确的 BREP 切片
"""

import os
import sys
import json
from typing import List, Tuple, Dict, Any
import math

try:
    import cadquery as cq
    from OCP.BRepAdaptor import BRepAdaptor_Curve
    HAS_CADQUERY = True
except ImportError as e:
    print(f"Import error: {e}", file=sys.stderr)
    HAS_CADQUERY = False


class ExactStepSlicer:
    """精确 STEP 切片器"""
    
    def __init__(self):
        if not HAS_CADQUERY:
            raise RuntimeError("cadquery not installed")
    
    def load_step(self, step_file: str) -> cq.Workplane:
        """
        加载 STEP 文件，返回 cadquery Workplane
        """
        if not os.path.exists(step_file):
            raise FileNotFoundError(f"STEP file not found: {step_file}")
        
        print(f"Loading STEP file: {step_file}", file=sys.stderr)
        wp = cq.importers.importStep(step_file)
        print(f"Loaded: {wp}", file=sys.stderr)
        return wp
    
    def get_bounds(self, wp: cq.Workplane) -> Dict[str, float]:
        """
        获取 Workplane 的边界框
        """
        # 获取形状的边界框
        shape = wp.val()
        bb = shape.BoundingBox()
        return {
            'xmin': bb.xmin,
            'ymin': bb.ymin, 
            'zmin': bb.zmin,
            'xmax': bb.xmax,
            'ymax': bb.ymax,
            'zmax': bb.zmax,
            'width': bb.xmax - bb.xmin,
            'depth': bb.ymax - bb.ymin,
            'height': bb.zmax - bb.zmin
        }
    
    def discretize_edge(self, edge, num_points: int = 20) -> List[Tuple[float, float, float]]:
        """
        将一条边离散化为点列表
        edge: cadquery.occ_impl.shapes.Edge 对象
        returns: list of (x, y, z) tuples
        """
        # 获取 OCP 边
        occ_edge = edge.wrapped
        
        # 创建适配器曲线
        adaptor = BRepAdaptor_Curve(occ_edge)
        
        # 获取参数范围
        first = adaptor.FirstParameter()
        last = adaptor.LastParameter()
        
        points = []
        for i in range(num_points):
            # 均匀参数采样
            if num_points == 1:
                u = first
            else:
                u = first + i * (last - first) / (num_points - 1)
            
            pnt = adaptor.Value(u)
            points.append((pnt.X(), pnt.Y(), pnt.Z()))
        
        return points
    
    def slice_at_z(self, wp: cq.Workplane, z: float) -> List[List[Tuple[float, float]]]:
        """
        在给定 Z 高度切片，返回轮廓点列表（每个轮廓是 (x,y) 列表）
        """
        # 计算截面
        section = wp.section(height=z)
        
        # 获取线框
        wires = section.wires()
        if wires.size() == 0:
            return []
        
        contours = []
        
        for wire_wp in wires.all():
            wire = wire_wp.val()  # 线框形状
            edges = wire.Edges()  # 获取边列表
            
            # 离散化每条边
            contour_points = []
            for edge in edges:
                # 对于每条边，我们采样点（排除最后一个点，因为下一条边的起点会重复）
                points = self.discretize_edge(edge, num_points=10)
                # 移除最后一个点（除非是闭合环）
                if len(points) > 1:
                    contour_points.extend(points[:-1])
                else:
                    contour_points.extend(points)
            
            # 转换为 2D 点（Z 应为常数）
            if contour_points:
                # 验证 Z 坐标是否一致（在公差范围内）
                z_values = [p[2] for p in contour_points]
                avg_z = sum(z_values) / len(z_values)
                # 转换为 2D
                contour_2d = [(p[0], p[1]) for p in contour_points]
                contours.append(contour_2d)
        
        return contours
    
    def slice(self, step_file: str, layer_height: float = 2.0) -> List[Dict[str, Any]]:
        """
        主切片函数
        返回切片列表，每个切片包含：
          - z: 切片高度
          - contours: 轮廓点列表（每个轮廓是 (x,y) 列表）
        """
        wp = self.load_step(step_file)
        bounds = self.get_bounds(wp)
        
        z_min = bounds['zmin']
        z_max = bounds['zmax']
        
        slices = []
        z = z_min + layer_height / 2.0
        
        while z <= z_max:
            contours = self.slice_at_z(wp, z)
            if contours:
                slices.append({
                    'z': z,
                    'contours': contours,
                    'num_contours': len(contours)
                })
            
            z += layer_height
        
        return slices
    
    def generate_gcode(self, slices: List[Dict], params: Dict) -> str:
        """
        从切片生成 G 代码
        """
        gcode_lines = []
        
        # 文件头
        gcode_lines.append("; ============================================")
        gcode_lines.append("; G-code generated by Exact STEP Slicer")
        gcode_lines.append("; ============================================")
        gcode_lines.append(f"; Tool Diameter: {params.get('tool_diameter', 6.0)} mm")
        gcode_lines.append(f"; Feed Rate: {params.get('feed_rate', 800)} mm/min")
        gcode_lines.append(f"; Spindle Speed: {params.get('spindle_speed', 3000)} RPM")
        gcode_lines.append(f"; Layer Height: {params.get('layer_height', 2.0)} mm")
        gcode_lines.append("")
        
        # 初始化
        gcode_lines.append("G90 ; Absolute positioning")
        gcode_lines.append("G21 ; Metric units (mm)")
        gcode_lines.append("G17 ; XY plane selection")
        gcode_lines.append("G40 ; Cancel tool radius compensation")
        gcode_lines.append("G49 ; Cancel tool length compensation")
        gcode_lines.append("G80 ; Cancel fixed cycles")
        gcode_lines.append("")
        
        # 主轴启动
        gcode_lines.append(f"M3 S{params.get('spindle_speed', 3000)} ; Spindle on")
        gcode_lines.append("G4 P3 ; Wait for spindle")
        gcode_lines.append("")
        
        safe_height = params.get('safe_height', 10.0)
        
        # 移动到安全高度
        gcode_lines.append(f"G0 Z{safe_height:.3f} ; Rapid to safe height")
        
        # 逐层加工
        for i, slice_data in enumerate(slices):
            z = slice_data['z']
            contours = slice_data.get('contours', [])
            
            if not contours:
                continue
            
            gcode_lines.append(f"; === Layer {i+1}, Z = {z:.3f} mm ===")
            
            # 下刀
            gcode_lines.append(f"G1 Z{z:.3f} F{params.get('plunge_feed', 400)} ; Plunge")
            
            # 切削每个轮廓
            for j, contour in enumerate(contours):
                if len(contour) < 2:
                    continue
                
                # 移动到轮廓起点
                x, y = contour[0]
                gcode_lines.append(f"G0 X{x:.3f} Y{y:.3f}")
                
                # 切削轮廓
                for point in contour[1:]:
                    x, y = point
                    gcode_lines.append(f"G1 X{x:.3f} Y{y:.3f} F{params.get('feed_rate', 800)}")
                
                # 闭合轮廓
                if len(contour) > 1:
                    x, y = contour[0]
                    gcode_lines.append(f"G1 X{x:.3f} Y{y:.3f}")
            
            # 抬刀
            gcode_lines.append(f"G0 Z{safe_height:.3f} ; Retract")
            gcode_lines.append("")
        
        # 结束
        gcode_lines.append("G0 Z50 ; Tool change height")
        gcode_lines.append("G0 X0 Y0 ; Return to origin")
        gcode_lines.append("M5 ; Spindle stop")
        gcode_lines.append("M30 ; Program end")
        gcode_lines.append("%")
        
        return "\n".join(gcode_lines)


def main():
    """命令行入口点"""
    if len(sys.argv) < 2:
        print("Usage: python exact_step_slicer.py <step_file> [layer_height]", file=sys.stderr)
        sys.exit(1)
    
    step_file = sys.argv[1]
    layer_height = float(sys.argv[2]) if len(sys.argv) > 2 else 2.0
    
    if not os.path.exists(step_file):
        print(f"Error: File not found: {step_file}", file=sys.stderr)
        sys.exit(1)
    
    try:
        slicer = ExactStepSlicer()
        slices = slicer.slice(step_file, layer_height)
        
        print(f"Slices: {len(slices)}", file=sys.stderr)
        for i, slice_data in enumerate(slices):
            z = slice_data['z']
            contours = slice_data['contours']
            print(f"  Slice {i+1}: Z={z:.3f}, contours={len(contours)}", file=sys.stderr)
            for j, contour in enumerate(contours):
                print(f"    Contour {j+1}: {len(contour)} points", file=sys.stderr)
        
        # 生成 G-code
        params = {
            'layer_height': layer_height,
            'tool_diameter': 6.0,
            'feed_rate': 800,
            'spindle_speed': 3000,
            'safe_height': 10.0,
            'plunge_feed': 400
        }
        gcode = slicer.generate_gcode(slices, params)
        
        # 输出 G-code
        print(gcode)
        
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        import traceback
        traceback.print_exc(file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()