import { Router } from "express";
import { z } from "zod";

const router = Router();

// ============ G代码生成请求验证 ============

const generateGcodeRequestSchema = z.object({
  modelBounds: z.object({
    minX: z.number(),
    maxX: z.number(),
    minY: z.number(),
    maxY: z.number(),
    minZ: z.number(),
    maxZ: z.number(),
  }),
  params: z.object({
    feedRate: z.number().positive(),
    spindleSpeed: z.number().positive(),
    cuttingDepth: z.number().positive(),
    stepOver: z.number().positive(),
    toolDiameter: z.number().positive(),
    safeHeight: z.number().nonnegative(),
    retractHeight: z.number().nonnegative(),
    coolantEnabled: z.boolean(),
    finishPass: z.boolean(),
    finishPassAllowance: z.number().nonnegative(),
  }),
});

export type GenerateGcodeRequest = z.infer<typeof generateGcodeRequestSchema>;

// ============ G代码生成 ============

router.post("/generate", async (req, res) => {
  try {
    const validation = generateGcodeRequestSchema.safeParse(req.body);
    
    if (!validation.success) {
      res.status(400).json({ 
        success: false, 
        error: "参数校验失败", 
        details: validation.error.flatten() 
      });
      return;
    }

    const { modelBounds, params } = validation.data;
    const gcode = generateGCode(modelBounds, params);
    const stats = calculateGCodeStats(gcode);

    res.json({
      success: true,
      gcode,
      stats,
      generatedAt: new Date().toISOString(),
    });
  } catch (error) {
    console.error("G-code generation error:", error);
    res.status(500).json({ success: false, error: "G代码生成失败" });
  }
});

// ============ 下载G代码 ============

router.get("/download", async (req, res) => {
  const { gcode, filename } = req.query;

  if (!gcode || typeof gcode !== "string") {
    res.status(400).json({ success: false, error: "缺少 G代码数据" });
    return;
  }

  const safeFilename = (filename as string || "toolpath").replace(/[^a-zA-Z0-9_-]/g, "_");
  res.setHeader("Content-Type", "text/plain; charset=utf-8");
  res.setHeader("Content-Disposition", `attachment; filename="${safeFilename}.nc"`);
  res.send(gcode);
});

// ============ G代码生成算法 ============

interface MachiningParams {
  feedRate: number;
  spindleSpeed: number;
  cuttingDepth: number;
  stepOver: number;
  toolDiameter: number;
  safeHeight: number;
  retractHeight: number;
  coolantEnabled: boolean;
  finishPass: boolean;
  finishPassAllowance: number;
}

function generateGCode(
  bounds: GenerateGcodeRequest["modelBounds"],
  params: MachiningParams
): string {
  const lines: string[] = [];
  const { minX, maxX, minY, maxY, minZ, maxZ } = bounds;

  // 文件头
  lines.push("; ============================================");
  lines.push("; Generated by STEP to G-Code Converter");
  lines.push("; ============================================");
  lines.push(`; Generated at: ${new Date().toISOString()}`);
  lines.push("; --------------------------------------------");
  lines.push(`; Tool Diameter: ${params.toolDiameter} mm`);
  lines.push(`; Spindle Speed: ${params.spindleSpeed} RPM`);
  lines.push(`; Feed Rate: ${params.feedRate} mm/min`);
  lines.push(`; Cut Depth: ${params.cuttingDepth} mm`);
  lines.push(`; Step Over: ${params.stepOver} mm`);
  lines.push(`; Safe Height: ${params.safeHeight} mm`);
  lines.push("; --------------------------------------------");
  lines.push("");

  // 初始化
  lines.push("G90 ; Absolute positioning");
  lines.push("G21 ; Metric units (mm)");
  lines.push("G17 ; XY plane selection");
  lines.push("G40 ; Cancel tool radius compensation");
  lines.push("G49 ; Cancel tool length compensation");
  lines.push("G80 ; Cancel fixed cycles");
  lines.push("");

  // 主轴启动
  lines.push(`M3 S${params.spindleSpeed} ; Spindle on, clockwise`);
  lines.push("G4 P3 ; Wait for spindle to reach speed");
  lines.push("");

  // 冷却液
  if (params.coolantEnabled) {
    lines.push("M8 ; Coolant on");
    lines.push("");
  }

  // 刀具补偿开启
  lines.push(`G41 D1 ; Tool radius compensation left (D=${params.toolDiameter / 2})`);
  lines.push("");

  // 计算层数
  const totalDepth = maxZ - minZ;
  const numLayers = Math.ceil(totalDepth / params.cuttingDepth);

  // 初始移动
  lines.push(`G0 Z${params.safeHeight.toFixed(3)} ; Rapid to safe height`);
  lines.push(`X${minX.toFixed(3)} Y${minY.toFixed(3)} ; Rapid to start position`);
  lines.push("");

  // 分层切削
  for (let layer = 0; layer < numLayers; layer++) {
    const currentZ = maxZ - layer * params.cuttingDepth;
    const nextZ = Math.max(minZ, currentZ - params.cuttingDepth);

    lines.push(`; === Layer ${layer + 1}/${numLayers}, Z = ${currentZ.toFixed(3)} mm ===`);

    // 下刀
    lines.push(`G1 Z${currentZ.toFixed(3)} F${(params.feedRate / 2).toFixed(0)} ; Plunge down`);

    // 螺旋下刀（第一层）
    if (layer === 0 && params.cuttingDepth > 0.5) {
      const centerX = (minX + maxX) / 2;
      const centerY = (minY + maxY) / 2;
      const helixRadius = Math.min((maxX - minX) / 4, (maxY - minY) / 4, 5);

      lines.push(`G2 I${helixRadius.toFixed(3)} J0 Z${nextZ.toFixed(3)} F${params.feedRate} ; Helical plunge`);
    }

    // 矩形轮廓切削 - 简单往复切削
    const numPassesX = Math.ceil((maxX - minX) / params.stepOver);
    
    for (let pass = 0; pass <= numPassesX; pass++) {
      const x = minX + pass * params.stepOver;
      const yStart = pass % 2 === 0 ? minY : maxY;
      const yEnd = pass % 2 === 0 ? maxY : minY;
      
      lines.push(`G1 X${x.toFixed(3)} Y${yStart.toFixed(3)} F${params.feedRate}`);
      if (yEnd !== yStart) {
        lines.push(`G1 Y${yEnd.toFixed(3)}`);
      }
    }

    // 抬刀
    lines.push(`G0 Z${params.safeHeight.toFixed(3)} ; Retract to safe height`);
    lines.push("");
  }

  // 精加工
  if (params.finishPass) {
    lines.push("; === Finish Pass ===");
    const finishZ = minZ + params.finishPassAllowance;
    lines.push(`G1 Z${finishZ.toFixed(3)} F${params.feedRate * 0.5}`);

    // 精加工轮廓
    lines.push(`G1 X${maxX.toFixed(3)} Y${maxY.toFixed(3)} F${params.feedRate}`);
    lines.push(`G1 Y${minY.toFixed(3)}`);
    lines.push(`G1 X${minX.toFixed(3)}`);
    lines.push(`G1 Y${maxY.toFixed(3)}`);
    lines.push(`G1 X${maxX.toFixed(3)}`);

    lines.push(`G0 Z${params.safeHeight.toFixed(3)}`);
    lines.push("");
  }

  // 返回原点
  lines.push("G0 Z50 ; Retract to tool change position");
  lines.push("G0 X0 Y0 ; Return to work origin");
  lines.push("");

  // 结束
  if (params.coolantEnabled) {
    lines.push("M9 ; Coolant off");
  }
  lines.push("M5 ; Spindle stop");
  lines.push("M30 ; Program end");
  lines.push("%");

  return lines.join("\n");
}

// ============ 统计计算 ============

function calculateGCodeStats(gcode: string): {
  totalLines: number;
  estimatedTime: number;
  toolpathLength: number;
} {
  const lines = gcode.split("\n").filter((line) => {
    const trimmed = line.trim();
    return trimmed && !trimmed.startsWith(";");
  });

  let totalDistance = 0;
  let currentX = 0,
    currentY = 0,
    currentZ = 0;

  for (const line of lines) {
    const xMatch = line.match(/X([-+]?[0-9]*\.?[0-9]+)/);
    const yMatch = line.match(/Y([-+]?[0-9]*\.?[0-9]+)/);
    const zMatch = line.match(/Z([-+]?[0-9]*\.?[0-9]+)/);

    let newX = xMatch ? parseFloat(xMatch[1]) : currentX;
    let newY = yMatch ? parseFloat(yMatch[1]) : currentY;
    let newZ = zMatch ? parseFloat(zMatch[1]) : currentZ;

    const dx = newX - currentX;
    const dy = newY - currentY;
    const dz = newZ - currentZ;
    totalDistance += Math.sqrt(dx * dx + dy * dy + dz * dz);

    currentX = newX;
    currentY = newY;
    currentZ = newZ;
  }

  // 估算加工时间（秒），假设平均进给速度 600 mm/min
  const estimatedTime = Math.round((totalDistance / 600) * 60);

  return {
    totalLines: lines.length,
    estimatedTime,
    toolpathLength: Math.round(totalDistance),
  };
}

export default router;
