"use client";

import { useState, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FileUpload } from "./components/file-upload";
import { ParametersPanel, type MachiningParameters } from "./components/parameters-panel";
import { ToolpathPreview } from "./components/toolpath-preview";
import { GcodeViewer } from "./components/gcode-viewer";
import { Loader2, Play, AlertCircle } from "lucide-react";
import { axiosForBackend } from "@lark-apaas/client-toolkit-lite";

interface ToolpathPoint {
  x: number;
  y: number;
  z: number;
  type?: "rapid" | "feed" | "plunge" | "retract";
}

interface ModelBounds {
  minX: number;
  maxX: number;
  minY: number;
  maxY: number;
  minZ: number;
  maxZ: number;
}

interface GcodeResult {
  gcode: string;
  toolpath?: ToolpathPoint[];
  stats?: {
    totalLines: number;
    estimatedTime: number;
    toolpathLength: number;
  };
}

const defaultParameters: MachiningParameters = {
  feedRate: 800,
  spindleSpeed: 3000,
  cuttingDepth: 2.0,
  stepOver: 0.5,
  toolDiameter: 6.0,
  safeHeight: 10.0,
  retractHeight: 3.0,
  coolantEnabled: true,
  finishPass: true,
  finishPassAllowance: 0.2,
};

// 模拟刀路生成（实际应用中应调用后端API）
function generateSimulatedToolpath(bounds: ModelBounds, params: MachiningParameters): ToolpathPoint[] {
  const points: ToolpathPoint[] = [];
  const { minX, maxX, minY, maxY, minZ, maxZ } = bounds;
  const numLayers = Math.ceil((maxZ - minZ) / params.cuttingDepth);
  
  // 起始点
  points.push({ x: minX, y: minY, z: maxZ + params.safeHeight, type: "rapid" });
  
  for (let layer = 0; layer < numLayers; layer++) {
    const currentZ = maxZ - layer * params.cuttingDepth;
    const nextZ = Math.max(minZ, currentZ - params.cuttingDepth);
    
    // 下刀
    points.push({ x: minX, y: minY, z: currentZ, type: "plunge" });
    
    // 矩形轮廓切削
    const stepsX = Math.ceil((maxX - minX) / params.stepOver);
    const stepsY = Math.ceil((maxY - minY) / params.stepOver);
    
    for (let i = 0; i <= stepsX; i++) {
      const x = minX + i * params.stepOver;
      const y = (i % 2 === 0) ? minY : maxY;
      points.push({ x, y, z: currentZ, type: "feed" });
    }
    
    for (let i = 0; i <= stepsY; i++) {
      const y = minY + i * params.stepOver;
      const x = (i % 2 === 0) ? maxX : minX;
      points.push({ x, y, z: currentZ, type: "feed" });
    }
    
    // 抬刀
    points.push({ x: minX, y: minY, z: maxZ + params.safeHeight, type: "retract" });
    
    // 快速移动到下一层起点
    points.push({ x: minX, y: minY, z: maxZ + params.safeHeight, type: "rapid" });
  }
  
  // 返回原点
  points.push({ x: 0, y: 0, z: maxZ + params.safeHeight, type: "rapid" });
  
  return points;
}

// 模拟G代码生成
function generateSimulatedGcode(bounds: ModelBounds, params: MachiningParameters): string {
  const lines: string[] = [];
  const { minX, maxX, minY, maxY, minZ, maxZ } = bounds;
  
  // 文件头
  lines.push("; ============================================");
  lines.push("; Generated by STEP to G-Code Converter");
  lines.push("; ============================================");
  lines.push(`; Generated at: ${new Date().toISOString()}`);
  lines.push("; --------------------------------------------");
  lines.push(`; Material: Aluminum (6061)`);
  lines.push(`; Tool Diameter: ${params.toolDiameter} mm`);
  lines.push(`; Spindle Speed: ${params.spindleSpeed} RPM`);
  lines.push(`; Feed Rate: ${params.feedRate} mm/min`);
  lines.push(`; Cut Depth: ${params.cuttingDepth} mm`);
  lines.push(`; Step Over: ${params.stepOver} mm`);
  lines.push(`; Safe Height: ${params.safeHeight} mm`);
  lines.push("; --------------------------------------------");
  lines.push("");
  
  // 初始化
  lines.push("G90 ; Absolute positioning");
  lines.push("G21 ; Metric units (mm)");
  lines.push("G17 ; XY plane selection");
  lines.push("G40 ; Cancel tool radius compensation");
  lines.push("G49 ; Cancel tool length compensation");
  lines.push("G80 ; Cancel fixed cycles");
  lines.push("");
  
  // 主轴启动
  lines.push(`M3 S${params.spindleSpeed} ; Spindle on, clockwise, ${params.spindleSpeed} RPM`);
  lines.push(`G4 P3 ; Wait for spindle to reach speed`);
  lines.push("");
  
  // 刀具补偿开启
  lines.push(`G41 D1 ; Tool radius compensation left`);
  lines.push("");
  
  // 计算层数
  const numLayers = Math.ceil((maxZ - minZ) / params.cuttingDepth);
  
  // 初始移动到安全高度
  lines.push(`G0 Z${params.safeHeight.toFixed(3)} ; Rapid to safe height`);
  lines.push(`X${minX.toFixed(3)} Y${minY.toFixed(3)} ; Rapid to start position`);
  lines.push("");
  
  // 分层切削
  for (let layer = 0; layer < numLayers; layer++) {
    const currentZ = maxZ - layer * params.cuttingDepth;
    const nextZ = Math.max(minZ, currentZ - params.cuttingDepth);
    
    lines.push(`; === Layer ${layer + 1}/${numLayers}, Z = ${currentZ.toFixed(3)} mm ===`);
    
    // 下刀
    lines.push(`G1 Z${currentZ.toFixed(3)} F${(params.feedRate / 2).toFixed(0)} ; Plunge down`);
    
    // 螺旋下刀（第一层）
    if (layer === 0) {
      const centerX = (minX + maxX) / 2;
      const centerY = (minY + maxY) / 2;
      const helixRadius = Math.min((maxX - minX) / 4, (maxY - minY) / 4);
      
      lines.push(`G2 I${helixRadius.toFixed(3)} J0 Z${nextZ.toFixed(3)} F${params.feedRate} ; Helical plunge`);
    }
    
    // 矩形轮廓切削
    lines.push(`G1 X${maxX.toFixed(3)} Y${maxY.toFixed(3)} F${params.feedRate} ; Cut to corner 1`);
    lines.push(`G1 Y${minY.toFixed(3)} ; Cut to corner 2`);
    lines.push(`G1 X${minX.toFixed(3)} ; Cut to corner 3`);
    lines.push(`G1 Y${maxY.toFixed(3)} ; Cut to corner 4`);
    lines.push(`G1 X${maxX.toFixed(3)} ; Return to start`);
    
    // 抬刀
    lines.push(`G0 Z${params.safeHeight.toFixed(3)} ; Retract to safe height`);
    lines.push("");
  }
  
  // 精加工（如果启用）
  if (params.finishPass) {
    lines.push("; === Finish Pass ===");
    const finishZ = minZ + params.finishPassAllowance;
    lines.push(`G1 Z${finishZ.toFixed(3)} F${params.feedRate * 0.5} ; Move to finish depth`);
    lines.push(`G1 X${maxX.toFixed(3)} Y${maxY.toFixed(3)} F${params.feedRate} ; Cut finish contour`);
    lines.push(`G1 Y${minY.toFixed(3)} ;`);
    lines.push(`G1 X${minX.toFixed(3)} ;`);
    lines.push(`G1 Y${maxY.toFixed(3)} ;`);
    lines.push(`G1 X${maxX.toFixed(3)} ;`);
    lines.push(`G0 Z${params.safeHeight.toFixed(3)} ;`);
    lines.push("");
  }
  
  // 返回原点
  lines.push("G0 Z50 ; Retract to tool change position");
  lines.push("G0 X0 Y0 ; Return to work origin");
  lines.push("");
  
  // 结束
  lines.push("M5 ; Spindle stop");
  lines.push("M30 ; Program end");
  lines.push("%");
  
  return lines.join("\n");
}

export default function HomePage() {
  const [file, setFile] = useState<File | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [processingStep, setProcessingStep] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [parameters, setParameters] = useState<MachiningParameters>(defaultParameters);
  const [modelBounds, setModelBounds] = useState<ModelBounds | null>(null);
  const [toolpath, setToolpath] = useState<ToolpathPoint[]>([]);
  const [gcode, setGcode] = useState<string>("");

  const handleFileSelect = useCallback(async (selectedFile: File) => {
    setFile(selectedFile);
    setError(null);
    setIsProcessing(true);
    setProcessingStep("上传并解析 STEP 文件...");

    try {
      const formData = new FormData();
      formData.append('stepFile', selectedFile);

      const response = await axiosForBackend.post('/api/step/parse', formData, {
        headers: {
          'Content-Type': 'multipart/form-data',
        },
        onUploadProgress: (progressEvent) => {
          if (progressEvent.total) {
            const percent = Math.round((progressEvent.loaded * 100) / progressEvent.total);
            setProcessingStep(`上传中... ${percent}%`);
          }
        },
      });

      if (!response.data.success) {
        throw new Error(response.data.error || '文件解析失败');
      }

      const result = response.data.data;
      const bounds = result.geometry.bounds;
      const realBounds: ModelBounds = {
        minX: bounds.min.x,
        maxX: bounds.max.x,
        minY: bounds.min.y,
        maxZ: bounds.max.z,
        minY: bounds.min.y,
        maxY: bounds.max.y,
        minZ: bounds.min.z,
        maxZ: bounds.max.z,
      };

      setModelBounds(realBounds);
      
      // 显示解析模式
      if (response.data.simulated) {
        setError('注意：使用模拟数据，真实 STEP 解析需要安装 Python 依赖 (meshio, trimesh)');
      } else {
        setProcessingStep("真实 STEP 解析成功");
      }

      setProcessingStep("生成加工刀路...");

      // 使用真实边界生成模拟刀路（后续可替换为真实切片）
      const simulatedToolpath = generateSimulatedToolpath(realBounds, parameters);
      setToolpath(simulatedToolpath);
      
      const simulatedGcode = generateSimulatedGcode(realBounds, parameters);
      setGcode(simulatedGcode);

      setProcessingStep("完成");
      setTimeout(() => {
        setIsProcessing(false);
        setProcessingStep("");
      }, 500);

    } catch (err: any) {
      console.error('STEP 解析错误:', err);
      
      // 如果 API 失败，回退到模拟模式
      setProcessingStep("使用模拟数据回退...");
      
      setTimeout(() => {
        const simulatedBounds: ModelBounds = {
          minX: 0,
          maxX: 50 + Math.random() * 50,
          minY: 0,
          maxY: 30 + Math.random() * 30,
          minZ: 0,
          maxZ: 10 + Math.random() * 20,
        };

        setModelBounds(simulatedBounds);
        const simulatedToolpath = generateSimulatedToolpath(simulatedBounds, parameters);
        setToolpath(simulatedToolpath);
        const simulatedGcode = generateSimulatedGcode(simulatedBounds, parameters);
        setGcode(simulatedGcode);
        
        setIsProcessing(false);
        setProcessingStep("");
        setError('API 调用失败，使用模拟数据。确保后端服务运行正常。');
      }, 1000);
    }
  }, [parameters]);

  const handleGenerate = useCallback(async () => {
    if (!modelBounds) {
      setError("请先上传 STEP 文件");
      return;
    }

    setIsProcessing(true);
    setProcessingStep("重新生成刀路...");
    setError(null);

    try {
      // 重新生成刀路和G代码
      const newToolpath = generateSimulatedToolpath(modelBounds, parameters);
      setToolpath(newToolpath);
      
      const newGcode = generateSimulatedGcode(modelBounds, parameters);
      setGcode(newGcode);
      
    } catch (err) {
      setError("G代码生成失败，请重试");
      console.error(err);
    } finally {
      setIsProcessing(false);
      setProcessingStep("");
    }
  }, [modelBounds, parameters]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
      {/* Header */}
      <header className="border-b border-slate-700/50 bg-slate-900/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-[1600px] mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center">
                <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
                </svg>
              </div>
              <div>
                <h1 className="text-xl font-bold text-white tracking-tight">STEP to G-Code</h1>
                <p className="text-xs text-slate-400">CNC加工刀路生成器</p>
              </div>
            </div>
            <nav className="flex items-center gap-6">
              <a href="#upload" className="text-sm text-slate-300 hover:text-white transition-colors">上传</a>
              <a href="#parameters" className="text-sm text-slate-300 hover:text-white transition-colors">参数</a>
              <a href="#preview" className="text-sm text-slate-300 hover:text-white transition-colors">预览</a>
              <a href="#output" className="text-sm text-slate-300 hover:text-white transition-colors">输出</a>
            </nav>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-[1600px] mx-auto px-6 py-8">
        {/* Hero Section */}
        <section className="text-center mb-12">
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
            将 STEP 文件转换为
            <span className="bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent"> 精密加工刀路</span>
          </h2>
          <p className="text-lg text-slate-400 max-w-2xl mx-auto">
            上传您的 3D STEP 模型，配置加工参数，即可生成可导入 CNC 机床的 G-code 文件
          </p>
        </section>

        {/* Processing Status */}
        <AnimatePresence>
          {isProcessing && (
            <motion.div
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="mb-6 p-4 bg-cyan-500/10 border border-cyan-500/30 rounded-xl"
            >
              <div className="flex items-center gap-3">
                <Loader2 className="w-5 h-5 text-cyan-400 animate-spin" />
                <div>
                  <p className="text-sm font-medium text-cyan-400">{processingStep}</p>
                  <p className="text-xs text-slate-400 mt-0.5">正在处理您的文件...</p>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Error Display */}
        <AnimatePresence>
          {error && (
            <motion.div
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="mb-6 p-4 bg-red-500/10 border border-red-500/30 rounded-xl"
            >
              <div className="flex items-center gap-3">
                <AlertCircle className="w-5 h-5 text-red-400" />
                <p className="text-sm text-red-400">{error}</p>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Main Grid Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Left Column */}
          <div className="space-y-6">
            {/* File Upload Section */}
            <section id="upload" className="bg-slate-800/50 backdrop-blur-sm rounded-xl border border-slate-700 p-6">
              <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-cyan-500/20 text-cyan-400 text-sm flex items-center justify-center">1</span>
                上传 STEP 文件
              </h2>
              <FileUpload
                onFileSelect={handleFileSelect}
                file={file}
                isProcessing={isProcessing}
                error={error}
              />
              {file && !isProcessing && (
                <div className="mt-4 p-3 bg-slate-700/50 rounded-lg">
                  <p className="text-xs text-slate-400 mb-2">模型信息</p>
                  {modelBounds && (
                    <div className="grid grid-cols-3 gap-2 text-xs">
                      <div>
                        <span className="text-slate-500">X:</span>
                        <span className="text-white ml-1">{modelBounds.maxX.toFixed(1)} mm</span>
                      </div>
                      <div>
                        <span className="text-slate-500">Y:</span>
                        <span className="text-white ml-1">{modelBounds.maxY.toFixed(1)} mm</span>
                      </div>
                      <div>
                        <span className="text-slate-500">Z:</span>
                        <span className="text-white ml-1">{modelBounds.maxZ.toFixed(1)} mm</span>
                      </div>
                    </div>
                  )}
                </div>
              )}
            </section>

            {/* Parameters Section */}
            <section id="parameters" className="bg-slate-800/50 backdrop-blur-sm rounded-xl border border-slate-700 p-6">
              <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-cyan-500/20 text-cyan-400 text-sm flex items-center justify-center">2</span>
                加工参数
              </h2>
              <ParametersPanel
                parameters={parameters}
                onChange={setParameters}
              />
              
              {/* Generate Button */}
              <div className="mt-6 pt-4 border-t border-slate-700">
                <button
                  onClick={handleGenerate}
                  disabled={!file || isProcessing}
                  className={cn(
                    "w-full flex items-center justify-center gap-2 px-6 py-3 rounded-xl font-medium transition-all",
                    file && !isProcessing
                      ? "bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white shadow-lg shadow-cyan-500/25"
                      : "bg-slate-700 text-slate-500 cursor-not-allowed"
                  )}
                >
                  <Play className="w-5 h-5" />
                  {isProcessing ? "生成中..." : "生成 G-code"}
                </button>
              </div>
            </section>
          </div>

          {/* Right Column */}
          <div className="space-y-6">
            {/* Preview Section */}
            <section id="preview" className="bg-slate-800/50 backdrop-blur-sm rounded-xl border border-slate-700 p-6">
              <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-cyan-500/20 text-cyan-400 text-sm flex items-center justify-center">3</span>
                刀路预览
              </h2>
              <div className="h-[350px]">
                <ToolpathPreview
                  toolpath={toolpath}
                  modelBounds={modelBounds || undefined}
                />
              </div>
            </section>

            {/* G-code Output Section */}
            <section id="output" className="bg-slate-800/50 backdrop-blur-sm rounded-xl border border-slate-700 p-6">
              <h2 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                <span className="w-6 h-6 rounded-full bg-cyan-500/20 text-cyan-400 text-sm flex items-center justify-center">4</span>
                G-code 输出
              </h2>
              <div className="h-[300px]">
                <GcodeViewer
                  gcode={gcode}
                  filename={file ? file.name.replace(/\.(step|stp)$/i, ".nc") : "toolpath.nc"}
                />
              </div>
            </section>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-700/50 mt-16">
        <div className="max-w-[1600px] mx-auto px-6 py-6">
          <div className="flex items-center justify-between text-sm text-slate-500">
            <p>STEP to G-Code Generator · 精密加工刀路生成工具</p>
            <p>支持 STEP/AP-203/AP-214 格式</p>
          </div>
        </div>
      </footer>
    </div>
  );
}

// Helper function
function cn(...classes: (string | undefined | null | false)[]): string {
  return classes.filter(Boolean).join(" ");
}
